### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [the0demiurge/ShadowSocksShare-OpenShift#90]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 1.1.2. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary ssshare -w /tmp/ext ssshare==1.1.2
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting ssshare==1.1.2
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/56b/c05cd46692111/ssshare-1.1.2.tar.gz (5.0 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-ihrg8wi5/ssshare/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-ihrg8wi5/ssshare/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-ihrg8wi5/ssshare/pip-egg-info
         cwd: /tmp/pip-wheel-ihrg8wi5/ssshare/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-ihrg8wi5/ssshare/setup.py", line 6, in <module>
        with open('requirements.txt') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by the0demiurge** [comment]
The setup.py file is not functional, and this is not planned to be fixed for now. If you want to make use of this project, [this link](https://heroku.com/deploy?template=https://github.com/the0demiurge/ShadowSocksShare/tree/master) will help you to deploy this project to heroku.

**Comment by thatch** [comment]
sad face emoji, ok
